version: '3.9'
services:
  app:
    image: masto-alt-text:latest
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mastoalttext
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mastoalttextpassword
volumes:
  db-data:
